[phases.setup]
nixPkgs = ["...", "nodejs"]

[phases.install]
cmds = ["npm ci"]

[phases.build]
cmds = ["npm run build"]

[phases.migrate]
dependsOn = ["build"]
cmds = ["npm run migration:prod && node scripts/seed-admin.js"]

[start]
cmd = "node dist/main"
